format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: article
    margin-left: 1in
    margin-right: 1in
    lof: false
    lot: false
    number-sections: false
    highlight-style: github
    linkcolor: orange
    mainfont: Arial
    classoption: landscape
    # fontfamily: libertinus


